#pre-commit install --hook-type pre-push
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pipreqs-generate
        name: Generate requirements.txt (pipreqs)
        entry: pipreqs src/drivebox --force --mode no-pin --savepath requirements.txt
        language: system
        pass_filenames: false