repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [--fix]
        stages: [commit]
      - id: ruff-format
        stages: [commit]

  - repo: local
    hooks:
      - id: pipreqs-generate
        name: Generate requirements.txt (pipreqs)
        entry: pipreqs src/drivebox --force --mode no-pin --savepath requirements.txt
        language: system
        pass_filenames: false
        stages: [commit]
      
      # Add tests on PUSH later
      # - id: pytest
      #   name: Run tests
      #   entry: pytest
      #   language: system
      #   pass_filenames: false
      #   stages: [push]