name: Build and Release

on:
  push:
    branches: [ master ]   # build artifacts on every push
  release:
    types: [created]     # special actions only on release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pyinstaller

      - name: Download ffmpeg
        run: |
          python scripts/download_ffmpeg.py

      - name: Build executable
        run: |
          pyinstaller main.spec

      # Always upload artifacts (for dev/test)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: drivebox-${{ matrix.os }}
          path: dist/**

      # Only on release, upload to GitHub Releases
      - name: Upload to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**